name=input("Enter your name:")
marks=int(input("Enter your marks:"))
phoneNo=input("Enter your phone no:")
func="The name of student is {}, his marks is {} and phone number is {}.".format(name,marks,phoneNo)
print(func)